### ISSUE TITLE
Action can't find Doxyfile

### ISSUE THREAD

**Issue by Ben1980** [mattnotmitt/doxygen-action#1]
Thanks for the GitHub action.
The action can't find my Doxyfile which is in the repository root. How can i get it to run?
'doxyfile-path'
Required Path of the Doxyfile relative to the repository root. Default: ./Doxyfile.
```
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: ./Doxyfile
```
