### ISSUE TITLE
Request for working sample examples

### ISSUE THREAD

**Issue by JaehyunShim** [mattnotmitt/doxygen-action#12]
Hi @mattnotmitt 

I would like to ask if there is any sample example provided to show how this action should be used. I did as follows but it seems I am using it in a wrong way

doxygen.yml file: https://github.com/JaehyunShim/test/blob/master/.github/workflows/doxygen.yml
Doxyfile: https://github.com/JaehyunShim/test/blob/master/docs/Doxygen/Doxyfile
Action result: https://github.com/JaehyunShim/test/runs/2054847888?check_suite_focus=true#step:3:7

Thank you in advance,
Jaehyun

**Comment by mattnotmitt** [comment]
You seem to be setting your working directory to `submodule/` which doesn't exist in your repository - this was just an example in the README. There's an additional example in [mattnotmitt/DelaunayTriangulation](https://github.com/mattnotmitt/DelaunayTriangulation/blob/master/.github/workflows/build-test-docs.yml). 
Looking at your repo, this is the config I would use.
```yml
name: Doxygen

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  doxygen:
    runs-on: ubuntu-20.04
    steps:
      - uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'docs/Doxygen/Doxyfile'
```
