### ISSUE TITLE
Documentation: Full Paths

### ISSUE THREAD

**Issue by JackAtGaia** [mattnotmitt/doxygen-action#26]
Greetings, like the action.  Worked pretty flawlessly once I figured it out.

I am not sure if I am unique, but I like to specify things by full paths to be sure I have things specified correctly.

so, in my workflow, I created a directory to hold the output, and then did some search & replace on the doxyfile to match.
```
mkdir -p ${{ github.workspace }}/doxygen-output
          sed -i 's|@CMAKE_CURRENT_BINARY_DIR@|${{ github.workspace }}/doxygen-output|g' ${{ github.workspace }}/production/docs/doxyfile
          sed -i 's|@CMAKE_CURRENT_SOURCE_DIR@/../|${{ github.workspace }}/production|g' ${{ github.workspace }}/production/docs/doxyfile
```

After getting some errors, it took me a bit to figure out that I needed to replace `${{ github.workspace }}` with `/github/workspace` as it was being mounted inside a docker container.

That might be something you want to point out for people using full paths.

**Comment by ruffner** [comment]
I have a question about paths as well, I cannot seem to get the action to succeed, it either cant find the output folder or the Doxyfile that I have.

From you comment above I am wondering if I need to edit my Doxyfile to use this action of if it is a matter of my yaml config. 

I am trying to build docs with this action then deploy to github pages. Here is my full yaml

```
name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@1.9.3
      - uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: doc
```

In my repository (https://github.com/movetones/Gravitone_ArduinoLibrary) I have a Doxyfile in thr root directory and I want to put the output of Doxygen in to the ```doc/``` folder. 

Any responses are appreciated.
