### ISSUE TITLE
Generation of tree view is different using doxygen-action

### ISSUE THREAD

**Issue by samueltootle** [mattnotmitt/doxygen-action#35]
I am building my doxygen webpages locally on PopOS with doxygen v1.9.1 and I have set doxygen-action to use the same:

```
    - name: build fukahome doxy
      uses: mattnotmitt/doxygen-action@1.9.1
      with:
        working-directory: './'
        doxyfile-path: 'website.dox'
```

However, when the website gets built with doxygen-action, the sidebar tree view no longer groups subpages under pages as it does when I build the doxygen site locally.  Originally I was using doxygen-action@v1.9.5 which caused some issues which was later identified to be caused by a newer version of doxygen, but now I'm not sure what could be causing this.

Any ideas?
