### ISSUE TITLE
working-directory doesn't support absolute path

### ISSUE THREAD

**Issue by WentsingNee** [mattnotmitt/doxygen-action#38]
Thank you a lot for such a wonderful action!

In my initial version of workflow, I wrote the followings:

```yaml
      - name: Clone Kerbal
        uses: actions/checkout@v4
        with:
          repository: WentsingNee/Kerbal
          path: Kerbal
          submodules: 'true'

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: '${{github.workspace}}/Kerbal/doxygen'
          doxyfile-path: 'Doxyfile'
```

but the log said that the directory cannot be found:

```
Job Clone Kerbal:

...
/usr/bin/git config --global --add safe.directory /home/runner/work/Kerbal/Kerbal/Kerbal
...

Job Run Doxygen:
...
+ '[' '!' -d /home/runner/work/Kerbal/Kerbal/Kerbal/doxygen ]
+ echo 'Path /home/runner/work/Kerbal/Kerbal/Kerbal/doxygen could not be found!'
Path /home/runner/work/Kerbal/Kerbal/Kerbal/doxygen could not be found!
+ exit 1

```

I have to change the line

```
working-directory: '${{github.workspace}}/Kerbal/doxygen'
```

to

```
working-directory: 'Kerbal/doxygen'
```

and finally solve that problem

I suggest that you can mention this issue in readme to help the latecomers and save their time
