### ISSUE TITLE
Can't cd to set path

### ISSUE THREAD

**Issue by gmargari** [mattnotmitt/doxygen-action#4]
Hi mattnotmitt!

I'm trying to use the action while I have the Doxyfile in a `docs` folder on my repo: https://github.com/gmargari/cmake-gtest-ci

```
name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
    - name: "Run doxygen"
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        working-directory: "docs/"
```
and I'm getting:
```
/usr/bin/docker run --name be76db65e21b2a8f4f46e8996f5a075bb0e7ce_53da06 --label be76db --workdir /github/workspace --rm -e INPUT_WORKING-DIRECTORY -e INPUT_DOXYFILE-PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/cmake-gtest-ci/cmake-gtest-ci":"/github/workspace" be76db:65e21b2a8f4f46e8996f5a075bb0e7ce  "./Doxyfile" "docs/"
/entrypoint.sh: cd: line 5: can't cd to docs/: No such file or directory
Path docs/ could not be found!
File ./Doxyfile could not be found!
error: configuration file ./Doxyfile not found!
```
